includePatterns:
  - sourceProject: '{{ref(project.current.projectId)}}'
    sourceTask: qmgsanityprecog_landing_cdc-oyz8
    tablePattern: '%'
    schemaPattern: '%'
    type: TABLE
excludePatterns: []
explicitlySelected: []
