id: $replicate$dbo_employees
name: dbo_Employees
type: LANDING
tableDef:
  name: Employees
  dbSchema: '{{task.simple_landing-wgtz:null$_$dbo.schema}}'
  columns: []
  secureQri: ''
  fullLoadOnly: false
