properties:
  name: replication_CDC
  id: replicate_cdc_cdc-cmvz
  description: ''
  type: REPLICATION
settings:
  replicationAppRuntime:
    sourceCdcFetchIntervalMinutes: 60
  taskSettings:
    fullLoad: true
    applyChanges: true
    storeChanges: true
  storeChangesOptions:
    changeDataPartitioning:
      partitionBaseTime: 2025-11-24T09:07:10.7120000Z
    changeTableHeaderColumn:
      - id: STREAM_POSITION
        headerColumn: stream_position
        isChecked: false
      - id: TRANSACTION_ID
        headerColumn: transaction_id
        isChecked: false
  errorHandling:
    environmental:
      maximumRetrySettings:
        maximumRetry: ALWAYS
        count: 0
  targetEndpoint:
    targetConnection: '{{task.replicate_cdc_cdc-cmvz.targetConnection}}'
    targetStorageConnection: '{{task.replicate_cdc_cdc-cmvz.targetStorageConnection}}'
  dataProviderType: REPLICATE
