properties:
  id: survey_templates-oy0t
  name: survey_templates
  type: STORAGE
  inputDatasets:
    - datasetId: survey_templates
      name: survey_templates
      taskId: cmgsanityprecog_landing_reload-oy0f
  datasetAttributes:
    materialized: INHERIT
    hasHistory: INHERIT
    hasLiveViews: INHERIT
    hasChanges: INHERIT
    hasStandardViewsWithHeaders: INHERIT
    watermarkIncrementalSettings: INHERIT
    createExternalArtifacts: INHERIT
