properties:
  id: survey_details_pages_questions_answers_choices-oy0r
  name: survey_details_pages_questions_answers_choices
  type: STORAGE
  inputDatasets:
    - datasetId: survey_details_pages_questions_answers_choices
      name: survey_details_pages_questions_answers_choices
      taskId: cmgsanityprecog_landing_reload-oy0f
  datasetAttributes:
    materialized: INHERIT
    hasHistory: INHERIT
    hasLiveViews: INHERIT
    hasChanges: INHERIT
    hasStandardViewsWithHeaders: INHERIT
    watermarkIncrementalSettings: INHERIT
    createExternalArtifacts: INHERIT
