properties:
  id: surveys
  name: surveys
  type: LANDING
  inputDatasets:
    - type: TABLE
      datasetId: $external_data_provider$_surveys$_$Surveys
      name: surveys
      taskId: qmgsanityprecog_landing_cdc-oyz8
sourceTable:
  id: $external_data_provider$_surveys$_$Surveys
  name: surveys
  type: LANDING
  tableDef:
    datasetId: surveys
    dbTableId: surveys$_$Surveys
    entityId: surveys
