properties:
  id: categories
  name: Categories
  type: LANDING
  inputDatasets:
    - type: TABLE
      datasetId: $replicate$dbo_categories
      name: Categories
      taskId: replicate_cdc_cdc-cmvz
      schema: '{{task.replicate_cdc_cdc-cmvz:null$_$dbo.schema}}'
sourceTable:
  id: $replicate$dbo_categories
  name: dbo_Categories
  type: LANDING
  tableDef:
    dbSchema: '{{task.replicate_cdc_cdc-cmvz:null$_$dbo.schema}}'
