id: categories
name: Categories
type: LANDING
inputDatasets:
  - type: TABLE
    datasetId: $replicate$dbo_categories
    name: Categories
    projectId: '{{ref(project.current.projectId)}}'
    taskId: simple_landing-wgtz
    schema: '{{task.simple_landing-wgtz:null$_$dbo.schema}}'
virtualDataset: false
description: ''
