id: $replicate$dbo_customers
name: dbo_Customers
type: LANDING
tableDef:
  name: Customers
  dbSchema: '{{task.simple_landing-wgtz:null$_$dbo.schema}}'
  columns: []
  secureQri: ''
  fullLoadOnly: false
