properties:
  id: question_bank_modifiers
  name: question_bank_modifiers
  type: LANDING
  inputDatasets:
    - type: VIEW
      datasetId: $external_data_provider$_question_bank_modifiers$_$Question Bank
      name: question_bank_modifiers
      taskId: cmgsanityprecog_landing_reload-oy0f
sourceTable:
  id: $external_data_provider$_question_bank_modifiers$_$Question Bank
  name: question_bank_modifiers
  type: LANDING
  tableDef:
    datasetId: questionbankmodifiers
    dbTableId: question_bank_modifiers$_$Question Bank
    entityId: questionbankmodifiers
    fullLoadOnly: true
