properties:
  id: survey_details_pages_questions_answers_choices
  name: survey_details_pages_questions_answers_choices
  type: LANDING
  inputDatasets:
    - type: VIEW
      datasetId: $external_data_provider$_survey_details_pages_questions_answers_choices$_$Survey Details
      name: survey_details_pages_questions_answers_choices
      taskId: cmgsanityprecog_landing_reload-oy0f
sourceTable:
  id: $external_data_provider$_survey_details_pages_questions_answers_choices$_$Survey Details
  name: survey_details_pages_questions_answers_choices
  type: LANDING
  tableDef:
    datasetId: surveydetailspagesquestionsanswerschoices
    dbTableId: survey_details_pages_questions_answers_choices$_$Survey Details
    entityId: surveydetailspagesquestionsanswerschoices
    fullLoadOnly: true
