properties:
  id: survey_categories
  name: survey_categories
  type: LANDING
  inputDatasets:
    - type: VIEW
      datasetId: $external_data_provider$_survey_categories$_$Survey Categories
      name: survey_categories
      taskId: cmgsanityprecog_landing_reload-oy0f
sourceTable:
  id: $external_data_provider$_survey_categories$_$Survey Categories
  name: survey_categories
  type: LANDING
  tableDef:
    datasetId: surveycategories
    dbTableId: survey_categories$_$Survey Categories
    entityId: surveycategories
    fullLoadOnly: true
