sourceConnection: '{{task.lake_landing_new-v4jw.sourceConnection}}'
explicitlySelected:
  - name: Categories
    schema: '{{task.lake_landing_new-v4jw:null$_$dbo.schema}}'
    type: TABLE
    sourceTableId: $replicate$dbo_categories
