scheduling:
  - enabled: false
    schedulingType: EVENT_BASED
    timeBasedScheduling:
      schedule: []
      fullloadInterval: 0
    eventBasedScheduling:
      eventSchedulingType: ANY_INPUT_TASK
      triggerApps: []
    runOnReconnect: ONSCHEDULED
    id: schedule-ad6z
    name: Schedule
    description: ''
    version: 1
