includePatterns:
  - sourceProject: '{{ref(project.current.projectId)}}'
    sourceTask: qmgsanityprecog_storage_cdc-oyz9
    tablePattern: '%'
    schemaPattern: '%'
    type: TABLE
excludePatterns: []
explicitlySelected: []
