ordinal: 0
actionType: RENAME_COLUMN
scopeType: COLUMN
scope:
  whereOwnerName: '%'
  whereTableName: '%'
  whereColumnName: '%'
  whereDatatype: UNSPECIFIED
  whereColumnKeyAttribute: ANY
  whereColumnNullability: ANY
action:
  renameType: ADD_PREFIX
  value: Prefix
  applyColumnDatatype: false
  column:
    ordinal: 0
    nullable: true
    primaryKeyOrdinal: 0
    datatype:
      type: STRING
      length: 50
      precision: 0
      scale: 0
      originalTypeFull: ''
    flags: NONE
enabled: true
internalRule: false
name: Rule
id: rule-e3bh
description: ''
