includePatterns:
  - sourceProject: '{{ref(project.current.projectId)}}'
    sourceTask: simple_landing-wgtz
    tablePattern: '%'
    schemaPattern: '%'
    type: TABLE
excludePatterns: []
explicitlySelected: []
