ddlHandlingPolicy:
  addColumn: APPLY_TO_TARGET
  changeColumnType: IGNORE
  renameTable: SUSPEND_TABLE
  renameColumn: SUSPEND_TABLE
  dropTable: IGNORE
  dropColumn: IGNORE
  truncateTable: IGNORE
  createTable: APPLY_TO_TARGET
artifactsSettings:
  liveViewsEnabled: true
  historyEnabled: true
  materialized: true
  changeTablesEnabled: true
  currentTableSuffix: __current
  reloadType: COMPARE_AND_APPLY_WITH_DELETED_ROWS
  artifactsPrefix: ''
fullLoadOnly: false
artifactsLocation:
  internalSchema: '{{task.simple_storage-wgt0.internalSchema}}'
  taskSchema: '{{task.simple_storage-wgt0.taskSchema}}'
  databaseName: '{{task.simple_storage-wgt0.databaseName}}'
taskRuntime:
  tableUpdateConcurrency: 10
  warehouseSelection:
    warehouseName: '{{task.simple_storage-wgt0.warehouseName}}'
catalogIntegration:
  publishDatasets: false
tableTypeSettings:
  tableType: REGULAR
  icebergSettings:
    snowflakeExternalVolume: ''
    folderLocationType: DATA_ASSET_NAME
    specificFolder: ''
    enableOpenCatalogSync: false
    snowflakeOpenCatalog: ''
viewType: DEFAULT
