id: employees-wgt4
name: Employees
type: STORAGE
inputDatasets:
  - type: NONE
    datasetId: employees
    name: Employees
    projectId: '{{ref(project.current.projectId)}}'
    taskId: simple_landing-wgtz
datasetAttributes:
  materialized: INHERIT
  hasHistory: INHERIT
  hasLiveViews: INHERIT
  hasChanges: INHERIT
  hasStandardViewsWithHeaders: INHERIT
  watermarkIncrementalSettings: INHERIT
virtualDataset: false
description: ''
